### ISSUE TITLE
On Linux/X11 is there a way of keeping data in the clipboard after the program exits ?

### ISSUE THREAD

**Issue by grahampc** [OzymandiasTheGreat/klembord#1]
For example with the following:

`import klembord
import sys

klembord.init()
print(klembord.get_text())
klembord.set_text('some string')
sys.stdin.readline()`

The text 'some string' is in the clipboard while waiting for the sys.stdin.readline() input but once that line has been entered and the program exits the clipboard is empty.

The xclip program does leave the data it puts in the clipboard there after it exits. It would be useful if this module could do that as well.

**Comment by OzymandiasTheGreat** [comment]
Yes, there is! As of right now, anyway.
Update klembord and then call `klembord.store()` before application exit and clipboard contents will persist in most cases.
Some desktop environments don't follow clipboard manager spec exactly so this may not work (I'm looking at you, KDE...).

I implemented this weeks ago and forgot to push it out. So thanks for the reminder :grinning:

**Comment by grahampc** [comment]
Thanks. It made no difference for me (I run openbox as my desktop environment, I don't think this has a clipboard manager). I installed parcellite as a clipboard manager and the clipboard data is saved on exit with or without klembord.store()
