### ISSUE TITLE
get_text() after clear() waits forever

### ISSUE THREAD

**Issue by grahampc** [OzymandiasTheGreat/klembord#4]
I would expect klembord.clear() and klembord.set_text('') to have more or less the same effect.

This code waits forever (spins in lines 189 and 190 of klembord/xclipboard.py):

`import klembord
import time

klembord.init()
klembord.clear()
time.sleep(0.05)
print(klembord.get_text())`

It doesn't stop waiting even if another program puts something into the clipboard.

If klembord.clear() is changed to klembord.set_text('') it behaves as expected.

I am running on Fedora Linux with openbox desktop.

**Comment by OzymandiasTheGreat** [comment]
Thanks for reporting!
To be fair, setting clipboard to an empty string and clearing it are very different operations.
Back on topic, not sure what's going on here, but I added timeouts to ensure it doesn't hang infinitely.
